### ISSUE TITLE
as a user, I want to define expenses and incomes categories in order to manage my finacial transaction

### ISSUE THREAD

**Issue by Iwona007** [bycza-zagroda/epic#7]
As a user I have different kind of expenses and incomes. I can define, edit, find and delete category. Every transaction has type and category, category cannot be null. And every category has many transaction and category can be without transaction.

Fields:

    name

Default expenses categories:

    shopping
    clothes
    fuel
    entertainment
    eating
    others

Default incomes categories:

    salary
    my own business
    others

Before I click save I can cancel all action: add, edit, find, delete

After I click "save"/ "delete"/"edit" category I can receive 2 different information:
1. "Your expense/income category is added/edited/deleted successfully". After 3 sec this information disappear.
2. "Sorry. Something went wrong and the expense is not added. Contact administrator" After 3 sec this information disappear.
The same

After I clicked on delete category button I also receive warming:

"Are you sure to delete category and all related data? "

    If I chose "yes" my category and all related financial transaction are deleted.
    If I chose "cancel" my category and all related financial transaction are not removed. Notification is closed

**Comment by mirekgab** [comment]
Duplicated.
